createTime: '2021-01-26T18:11:35.763164058Z'
filter: |-
  resource.type="k8s_container" 
  resource.labels.container_name="socket" 
  severity="INFO" 
  textPayload:"SEND_MESSAGE about to emit"
labelExtractors:
  displayName: REGEXP_EXTRACT(textPayload, "\"connector_displayname\":\"([^\"]+)\"")
metricDescriptor:
  labels:
  - key: displayName
  metricKind: DELTA
  name: projects/prodigy-dev-1/metricDescriptors/logging.googleapis.com/user/logging/chat_messages_count
  type: logging.googleapis.com/user/logging/chat_messages_count
  unit: '1'
  valueType: INT64
name: logging/chat_messages_count
updateTime: '2021-02-02T19:38:13.725705281Z'
