# replicaCount x VUS = [total number of VUS]
replicaCount: 4

loadTest:
  vars:
    VUS: 100  # per worker
    HOLD_MINUTES: 60
    VUS_PER_MINUTE: 30

    # join and stay in the meeting
    CHAT_DURATION: 1800 # 1 h
    SKIP_JOIN_MESSAGE: 1 # no message after joining
    NEW_MESSAGE_INTERVAL: 40 # in seconds
    NEW_MESSAGE_CHANCE: 0.1 # % chance of sending a message
    SKIP_JOIN_API_CALLS: 1
    ENABLE_MPAAS: 1

    ANONYMOUS_RATE: 0.10
    DASHBOARD_VISIT_RATE: 0.01

    JOIN_TOPIC_ID: 5fd23dcb698b03fafe5897d1 # https://loganstaging2020.esna.com/spaces/5fd23dcb698b03fafe5897d1
    SPACES_URL: https://loganstaging2020.esna.com
    SPACES_API: "https://loganstaging2020apis.esna.com/api"
    CHAT_WS: "wss://loganstaging2020apis-socket.esna.com"
    # this var will ensure that DD will treat data from this load test separately, since both tests can have the same POD_INDEX
    POD_GROUP: secondary
    # DATA_PATH: ../data/users-chunked/users_0002.csv # smaller files, less memory used
