# https://taskfile.dev

version: '2'

vars:
  # SPACES_URL: https://spaces-sit.esna.com
  # SPACES_API: https://spaces-sitapis.esna.com/api
  # CHAT_WS: wss://spaces-sitapis-socket.esna.com

  SPACES_URL: https://loganstaging.esna.com
  SPACES_API: "https://loganstagingapis.esna.com/api"
  CHAT_WS: "wss://loganstagingapis-socket.esna.com"

  DATADOG_API_KEY: 411f6c91025bbdcba65fb3721d5ce4a4

includes:
  cloud: ./infra/Taskfile.yml

tasks:

  login-test:
    cmds:
      - k6 run -u 1 -d 1s src/login.js -e SPACES_API={{.SPACES_API}} -e SPACES_URL={{ .SPACES_URL }}

  join-test:
    cmds:
      - k6 run -u 1 -d 10s src/join.js -e SPACES_API={{.SPACES_API}} -e DEBUG=1 

  chat-test:
    cmds:
      - |
        k6 run -u 1 src/chat.js -e CHAT_WS={{.CHAT_WS}} -e SPACES_API={{.SPACES_API}} -e DEBUG=1 \
          -e CHAT_DURATION=36

  mpaas-test:
    cmds:
      - |
        k6 run -u 1 -d 10s src/mpaas.js -e CHAT_WS={{.CHAT_WS}} -e SPACES_API={{.SPACES_API}} \
          --insecure-skip-tls-verify

  anon-test:
    cmds:
      - k6 run -u 1 -d 1s src/login-anonymous.js -e SPACES_API={{.SPACES_API}}

  quick-run:
    cmds:
      - |
        k6 run src/spaces.test.js -e VUS=5 \
          -e SPACES_API={{.SPACES_API}} \
          -e CHAT_WS={{.CHAT_WS}} -e SPACES_URL={{ .SPACES_URL }} \
          -e CHAT_DURATION=3600 -e DEBUG=1 \
          -e NEW_MESSAGE_INTERVAL=60 -e SKIP_JOIN_MESSAGE=1 -e NEW_MESSAGE_CHANCE=0.70 \
          -e HOLD_MINUTES=120


  large-meeting-test:
    cmds:
      - |
        k6 run -u 3 -d 10m src/spaces.test.js \
          -e SPACES_API={{.SPACES_API}} \
          -e CHAT_WS={{.CHAT_WS}} -e SPACES_URL={{ .SPACES_URL }} \
          -e ANONYMOUS_RATE=0.2 -e DASHBOARD_VISIT_RATE=0.02 \
          -e DATA_PATH="../data/users-chunked/" -e DATA_FILE_PREFIX="users_" \
          -e SKIP_JOIN_MESSAGE=1 -e NEW_MESSAGE_CHANCE=0.1 \
          -e CHAT_DURATION=1800 \
          -e JOIN_TOPIC_ID=5fca9bf4a507404a1865ff1c \
          -e SKIP_JOIN_API_CALLS=1 -e ENABLE_MPAAS=1 \
          --insecure-skip-tls-verify


  run-long:
    cmds:
      - ulimit -n 20000
      - |
        k6 run --out=influxdb=http://localhost:8086/k6 -u 10 -d 10m \
          src/spaces.test.js \
          -e SPACES_API={{.SPACES_API}}  \
          -e SPACES_URL={{ .SPACES_URL }} \
          -e CHAT_WS={{.CHAT_WS}} \
          -e CHAT_DURATION=600 -e NEW_MESSAGE_INTERVAL=60




  split-data-file:
    dir: ./data
    cmds:
      # should have GNU split installed
      # brew install coreutils
      - rm -rf users-chunked
      - mkdir users-chunked
      - |
        {{if eq OS "darwin"}}g{{end}}split -d -a 4 -l 100 user-pwd-full.csv users-chunked/users_ --additional-suffix=.csv

  datadog-agent-start:
    cmds:
      - |
        DOCKER_CONTENT_TRUST=1 \
        docker run -d --rm \
            --name datadog \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -v /proc/:/host/proc/:ro \
            -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
            -e DD_SITE="datadoghq.com" \
            -e DD_API_KEY={{.DATADOG_API_KEY}} \
            -e DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1 \
            -p 8125:8125/udp \
            datadog/agent:latest

  datadog-agent-stop:
    cmds:
      - docker stop datadog

  run-local-w-datadog:
    deps: ['datadog-agent-start']
    cmds:
      # `sysctl kern.maxfiles` to see system limit
      # `ulimit -n` can only be set once, open new terminal to set new limit
      - |
        ulimit -n 50000 && \
        k6 run --out datadog \
          src/spaces.test.js  \
          -e SPACES_API={{.SPACES_API}}  \
          -e SPACES_URL={{ .SPACES_URL }} \
          -e CHAT_WS={{.CHAT_WS}} \
          -e DATA_PATH="../data/users-chunked/" \
          -e DATA_FILE_PREFIX="users_" \
          -e CHAT_DURATION=300

  grafana-start:
    cmds:
      - |
        docker-compose up -d \
          influxdb \
          grafana

  run-local:
    desc: Run load test locally
    cmds:
      - |
        ulimit -n 24000 && \
        k6 run --out=influxdb=http://localhost:8086/k6 \
          src/spaces.test.js \
          -e SPACES_API={{.SPACES_API}}  \
          -e SPACES_URL={{ .SPACES_URL }} \
          -e CHAT_WS={{.CHAT_WS}} \
          -e DATA_PATH="../data/users-chunked/" \
          -e DATA_FILE_PREFIX="users_" \
          -e CHAT_DURATION=70 -e NEW_MESSAGE_INTERVAL=40

  make-image:
    cmds:
      - task: split-data-file
      - task: cloud:push-image
