{{range $i, $e := until (.Values.replicaCount|int) }}
{{- $pod_index := $i | add1 -}}
{{/*
math here is not exact, e.g. `div 90 30 + 1 = 4`,  (but only 3 agents are necessary)
I cannot figure out how to make `div` returns floating number that can be rounded up with `coil`
*/}}
{{- $dd_agents_index := div $pod_index $.Values.datadog.pods_per_agent | add1  -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Chart.Name }}-{{ $pod_index }}
  labels:
    app: {{ $.Chart.Name }}-{{ $pod_index }}
spec:
  containers:
    - name: {{ $.Chart.Name }}-{{ $pod_index }}
      image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
      imagePullPolicy: {{ $.Values.image.pullPolicy }}
      env:
        - name: "POD_INDEX"
          value: {{ $pod_index| quote }}
        - name: "K6_OUT"
          value: "datadog"
        - name: "K6_DATADOG_ADDR"
          value: datadog-agent-{{ $dd_agents_index }}.{{ $.Release.Namespace }}.svc.cluster.local:8125
        {{- range $key, $value := $.Values.loadTest.vars }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
      resources:
        {{- toYaml $.Values.resources | nindent 8 }}
  initContainers:
  - name: init-datadog
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup datadog-agent-{{ $dd_agents_index }}.{{ $.Release.Namespace }}.svc.cluster.local; do echo waiting for datadog; sleep 2; done"]
  restartPolicy: Never
---
{{end}}
