substitutions:
  _BUILD_WORKER_IMAGE: "no"
  _VALUES_GROUP: default
  _REPLICA_COUNT: "3"
  _URL_FRONTEND: ""
  _URL_API: ""
  _URL_SOCKET: ""
  _GO_TASK_URL: https://github.com/go-task/task/releases/download/v3.9.0/task_linux_amd64.tar.gz


steps:

  - id: build image
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |
        cd ./k6
        if [[ "${_BUILD_WORKER_IMAGE}" == "yes" ]]; then  
          echo "download go-task"
          curl -SL ${_GO_TASK_URL} -o task.tar.gz && tar zxvf task.tar.gz    
          echo "building new image"
          ./task make-image
        fi

  - id: Start load tests
    name: 'gcr.io/$PROJECT_ID/k6-runner'
    entrypoint: '/bin/bash'
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |
        cd ./k6

        task cloud:kube-config

        export _VALUES_GROUP=$_VALUES_GROUP
        export _REPLICA_COUNT=$_REPLICA_COUNT
        export _URL_FRONTEND=$_URL_FRONTEND
        export _URL_API=$_URL_API
        export _URL_SOCKET=$_URL_SOCKET

        task cloud:run-with-params

options:
  dynamic_substitutions: true