steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/k6-runner:${_VERSION}', '--tag=gcr.io/$PROJECT_ID/k6-runner:latest', '.']

images:
  - 'gcr.io/$PROJECT_ID/k6-runner:${_VERSION}'
  - 'gcr.io/$PROJECT_ID/k6-runner:latest'
  
tags: ['cloud-builders-community']
substitutions:
  _VERSION: '1.0'

