apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-agent
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
      annotations: {}
    spec:
      containers:
      - name: agent
        image: "datadog/agent:7.19.0"
        imagePullPolicy: IfNotPresent
        command: ["agent", "start"]
        resources: {}
        ports:
        - containerPort: 8125
          name: dogstatsdport
          protocol: UDP
        env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: es-artillery-secret
              key: DD_API_KEY
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBERNETES
          value: "yes"
        - name: DOCKER_HOST
          value: unix:///host/var/run/docker.sock
        - name: DD_LOG_LEVEL
          value: "INFO"
        - name: DD_DOGSTATSD_PORT
          value: "8125"
        - name: DD_APM_ENABLED
          value: "false"
        - name: DD_LOGS_ENABLED
          value: "false"
        - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
          value: "false"
        - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
          value: "true"
        - name: DD_HEALTH_PORT
          value: "5555"
        - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /etc/datadog-agent
       
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
      initContainers:
      - name: init-volume
        image: "datadog/agent:7.19.0"
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
        - cp -r /etc/datadog-agent /opt
        volumeMounts:
        - name: config
          mountPath: /opt/datadog-agent
        resources: {}
      - name: init-config
        image: "datadog/agent:7.19.0"
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
        - for script in $(find /etc/cont-init.d/ -type f -name '*.sh' | sort) ; do
          bash $script ; done
        volumeMounts:
        - name: config
          mountPath: /etc/datadog-agent
       
        
        env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: es-artillery-secret
              key: DD_API_KEY
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBERNETES
          value: "yes"
        
        resources: {}
      volumes:
      - name: config
        emptyDir: {}
      nodeSelector:
        cloud.google.com/gke-nodepool: other-pool
      
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
spec:
  selector:
    app: datadog-agent
  ports:
    - protocol: UDP
      port: 8125
      targetPort: 8125